matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: '10'

      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: windows
      language: node_js
      node_js: '10'

branchs:
  only:
    - master

sudo: required

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - nvm install 7
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - npm install -g xvfb-maybe
  - yarn

script:
  - npm run lint
  - npm run pack

notifications:
  email: false
