matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: '10'

      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      language: node_js
      node_js: '10'

branchs:
  only:
    - master

sudo: required

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

if: tag IS present

script:
  - npm run lint

deploy:
  - provider: script
    script: npm run pack
    skip_cleanup: true
    on:
      tags: true
