os: osx
language: node_js
node_js:
  - '8'
branchs:
  only:
  - master
env:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache:
  directories:
    - 'node_modules'
script:
  - npm run lint
  - npm run build
