os: osx
osx_image: xcode9.4
language: node_js
node_js: '10'

env:
  # - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

branchs:
  only:
    - master

sudo: required

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - openssl aes-256-cbc -K $encrypted_eddd6ba770f1_key -iv $encrypted_eddd6ba770f1_iv -in keygen.yml.enc -out keygen.yml -d

script:
  - npm run lint
  - npm run pack
  # - npm run upload

after_script:
  - cd ./packages
  - git config --global user.name "${GT_USERNAME}"
  - git config --global user.email "${GT_EMAIL}"
  - git init
  - git add .
  - git commit -m "update app bundles"
  - git remote add origin https://${GT_USERNAME}:${GT_PASSWORD}@gitee.com/${GT_USERNAME}/altas.git
  - git push --progress -f origin master

notifications:
  email:
    recipients:
      - ${GT_EMAIL}
    on_success: always
    on_failure: always
