matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: '10'

      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      language: node_js
      node_js: '10'

branchs:
  only:
    - master

sudo: required

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - npm install

before_script:
  - if [ '$TRAVIS_OS_NAME' == 'linux' ] && [ '$TRAVIS_PULL_REQUEST' == 'false' ]; then
      sudo apt-get update;
      sudo apt-get install -y rpm;
    fi

script:
  - npm run lint
  - if [ '$TRAVIS_OS_NAME' == 'linux' ] && [ '$TRAVIS_PULL_REQUEST' == 'false' ]; then
      npm run pack;
    elif [ '$TRAVIS_OS_NAME' == 'osx' ] && [ '$TRAVIS_PULL_REQUEST' == 'false' ]; then
      npm run pack:win;
    else
      npm run build;
    fi

notifications:
  email: false
  