language: node_js

matrix:
  include:
    - os: linux
      node_js: 10
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar
      - snapd

branchs:
  only:
    - DaVinci

sudo: required
dist: trusty

install:
  - yarn

cache: yarn

before_install:
  - openssl aes-256-cbc -K $encrypted_eddd6ba770f1_key -iv $encrypted_eddd6ba770f1_iv -in keygen.yml.enc -out keygen.yml -d
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo snap install snapcraft --classic; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi

script:
  - npm run lint
  - npm run pack
  - npm run upload

after_script:
  - cd ./packages
  - git config --global user.name "${GT_USERNAME}"
  - git config --global user.email "${GT_EMAIL}"
  - git init
  - git add .
  - git commit -m "update app bundles"
  - git remote add origin https://${GT_USERNAME}:${GT_PASSWORD}@gitee.com/${GT_USERNAME}/altas.git
  - git push --progress -f origin master

notifications:
  email:
    recipients:
      - owlaford@gmail.com
    on_success: always
    on_failure: always
