os: windows
language: node_js
node_js: '12'

dist: trusty

env:
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

branchs:
  only:
    - DaVinci

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron-builder

before_install:
  - openssl aes-256-cbc -K $encrypted_eddd6ba770f1_key -iv $encrypted_eddd6ba770f1_iv -in keygen.yml.enc -out keygen.yml -d

script:
  - yarn pack:win
  - yarn upload:win

notifications:
  email:
    recipients:
      - owlaford@gmail.com
    on_success: always
    on_failure: always
