os: osx
osx_image: xcode9.4
language: node_js
node_js: '10'

env:
  # - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

branchs:
  only:
    - master

sudo: required

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - openssl aes-256-cbc -K $encrypted_eddd6ba770f1_key -iv $encrypted_eddd6ba770f1_iv -in sftpkey.enc -out sftpkey -d

script:
  - npm run lint
  - npm run pack
  - npm run upload

notifications:
  email: false
