os:
  - osx
  - windows

language: node_js

node_js: stable

branchs:
  only:
    - master

sudo: required

env:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - electron
    - 'node_modules'

script:
  - npm run lint
  - npm run pack
